### ISSUE TITLE
关于test.py的问题

### ISSUE THREAD

**Issue by caofaxin** [thunlp/LEVEN#1]
您好，请问gen_metic.py这个文件中的combined_top100.json文件是怎么生成的，您这个文件夹中是不是少了test.py呢

**Comment by yaof20** [comment]
> 您好，请问gen_metic.py这个文件中的combined_top100.json文件是怎么生成的，您这个文件夹中是不是少了test.py呢

Hi, `combined_top100.json` 是 LeCaRD数据集提供的，参见[这里](https://github.com/myx666/LeCaRD/tree/main/data/prediction).  

原先的SCR-Preprocess的Usage部分的第一点有一个typo，遗漏了prediction文件夹，现已修改，参见[这里](https://github.com/thunlp/LEVEN/tree/main/Downstreams/SCR/SCR-Preprocess#usage).
