### ISSUE TITLE
raw files 

### ISSUE THREAD

**Issue by mark12581** [thunlp/LEVEN#2]
Can you release your raw files,thx.

**Comment by yaof20** [comment]
> Can you release your raw files,thx.

We have provided as much information as we can in the published LEVEN dataset. Check [here](https://github.com/thunlp/LEVEN#overview) to download.

If the raw files you mentioned were the raw judgment documents, we don't have any plan to release them.

However, we have released the case number, as well as the case title, for each case we collected. You can use them to search for the raw file on [China Judgment Online](https://wenshu.court.gov.cn/) website.
