### ISSUE TITLE
关于训练轮数的问题

### ISSUE THREAD

**Issue by Superji-dev** [thunlp/LEVEN#3]
非常感谢作者开源了LEVEN数据集和相关baseline方法，但是我在调试DMBERT方式时得到的准确率，召回率和F1值为0，观察预测结果发现预测的类别均是第0类，所以请问作者在训练过程中是什么导致了这种情况的出现，是否和训练轮数有关？
希望能得到作者的答复！谢谢！

**Comment by yaof20** [comment]
> 非常感谢作者开源了LEVEN数据集和相关baseline方法，但是我在调试DMBERT方式时得到的准确率，召回率和F1值为0，观察预测结果发现预测的类别均是第0类，所以请问作者在训练过程中是什么导致了这种情况的出现，是否和训练轮数有关？ 希望能得到作者的答复！谢谢！

您好，可以参考DMBERT文件夹下提供的`run_train.sh`中所使用的参数。由于DMBERT是token_classification的范式，因此训练较慢。您可以尝试将batch size开大一些或者使用BERT+CRF这种sequence labeling的范式。

希望以上可以解决您的问题

**Comment by Superji-dev** [comment]
感谢作者的回复，我观察到，None类的数量远远大于其它类别的数量，如此悬殊的比例导致了模型偏向第0类，预测值为全0，因此准确率，召回率和F1值为0，请问作者对于这种长尾问题是如何解决的？另外在使用test.jsonl文件进行模型测试过程中，由于test.jsonl标签全为None，导致无法进行模型测试，请问作者是如何得到测试集指标的？

**Comment by yaof20** [comment]
> 感谢作者的回复，我观察到，None类的数量远远大于其它类别的数量，如此悬殊的比例导致了模型偏向第0类，预测值为全0，因此准确率，召回率和F1值为0，请问作者对于这种长尾问题是如何解决的？另外在使用test.jsonl文件进行模型测试过程中，由于test.jsonl标签全为None，导致无法进行模型测试，请问作者是如何得到测试集指标的？

训练数据中的非0标注是足够训练出一个效果不错的模型的，感觉可能是你在训练过程中哪里出了问题，可以再检查一下参数设置或者评测是否有问题。另外，我们近期会发布一个统一的事件检测/抽取的工具包，到时候关注试用一下；

test.jsonl标签全为None是我们隐藏了标注结果，您可以通过 [run_infer.sh](https://github.com/thunlp/LEVEN/blob/main/Baselines/DMBERT/run_infer.sh) 生成submission file，将结果提交至 [CAIL2022](http://cail.cipsc.org.cn/task1.html?raceID=1&cail_tag=2022) . 这几天测试平台正在最终调试，预计下周可以正式提交，欢迎关注:）
