### ISSUE TITLE
我想问下results_Bilstm.jsonl的结果怎么转化为对应的文字预测结果呢，里面都是ID

### ISSUE THREAD

**Issue by guocxian** [thunlp/LEVEN#4]

**Comment by yaof20** [comment]
您好，`.jsonl`文件是提交评测的格式，字段内容参考[这里](https://github.com/thunlp/LEVEN/blob/9a17123a790147149c515623aeb6e2031d70906e/Baselines/DMBERT/get_submission.py#L24)，里面的`id`对应的事件类型参考[这里](https://github.com/thunlp/LEVEN/blob/9a17123a790147149c515623aeb6e2031d70906e/Baselines/DMBERT/utils_ee.py#L29).
