### ISSUE TITLE
测试阶段的标签

### ISSUE THREAD

**Issue by Yyy11181** [thunlp/LEVEN#6]
你好 能够提供LEVEN数据的所有标签啊 目前测试阶段的标签没有发布啊

**Comment by yaof20** [comment]
hi, 测试集的标注我们是不公开的，你可以提交测试集预测结果至[CAIL](http://cail.cipsc.org.cn/task_summit.html?raceID=1&cail_tag=2022)获取测试集的评测指标。

CAIL现在是封测阶段，之后会持续开放提交，感谢关注！

**Comment by Yyy11181** [comment]
好的 感谢，祝学业顺利

**Comment by Yyy11181** [comment]
hello 想再请教几个问题 
第一，数据集中Negative_triggers 存在的意义是什么？可以完全不需要呀
第二 ，根据相关的结果 明显bert类的模型效果更好呀 LEVEN论文中 怎么说不怎么好？？
是我理解有问题吗？
![image](https://user-images.githubusercontent.com/96362397/206073046-cbbdcef6-05b6-416a-a09a-0aa602523bdf.png)
![image](https://user-images.githubusercontent.com/96362397/206073112-d42a3957-60f3-46bd-aff8-f04ac5e87256.png)
第三，论文中“It suggests that designing event-oriented pre-trained models is necessary for LED” 是什么意思啊？
再次感谢！！

**Comment by yaof20** [comment]
> 

* 问题1
给出统一的negative trigger是为了在评测时统一口径，避免不同的使用者在汇报结果时采用不同的negative triggers，从而进行公平、统一的评测。统一评测的问题可以参考我们新发布的[OmniEvent](https://github.com/THU-KEG/OmniEvent/tree/main/OmniEvent/evaluation#convert-the-predictions-of-different-paradigms-to-a-unified-candidate-set)工具包。
* 问题2
论文所描述的是“基于BERT的模型没有取得**significant 显著的**提升”，这里使用BERT类的模型只获得了很微弱的提升。相较于表格中其他的模型，BERT的复杂度要高很多，但带来的效果提升却不明显（通常其他任务可能会提升10个点以上）。
* 问题3
表明通用预训练模型在LED (Legal Event Detection)这个任务上的表现一般（没有带来非常明显的提升），因此我们考虑根据event设计预训练模型，期望获得性能更优越的模型。event-oriented pretrained models 相关工作可以参考[CLEVE](https://aclanthology.org/2021.acl-long.491.pdf)。

**Comment by Yyy11181** [comment]
好的 感谢您的悉心解答

**Comment by Yyy11181** [comment]
您好 测试阶段的标签可以拿来用吗？改进了模型 不支持你们测评的提交格式

**Comment by yaof20** [comment]
> 您好 测试阶段的标签可以拿来用吗？改进了模型 不支持你们测评的提交格式

您好，模型改进和测评提交格式是互不影响的。

您可以使用您改进之后的模型做inference，把inference的结果保存为提交格式即可。

祝顺利。

**Comment by Yyy11181** [comment]
我把数据的格式改变了 没有按句子级别来，导致在生成results.json 的时候不能正确生成

**Comment by Yyy11181** [comment]
方便开源一下吗？这样更可能促进这个LED领域的探索。 @yaof20

**Comment by yaof20** [comment]
> 我把数据的格式改变了 没有按句子级别来，导致在生成results.json 的时候不能正确生成

您好，这种情况您可以尝试保存每个sentence在您合并之后的文本中的offset，再按照此offset将inference的结果对应到原始的句子当中。

**Comment by Yyy11181** [comment]
您好 感谢您的提醒! 我是把基于句子级别的标签都打上了之后（还没有id化），之后把属于一个文档中的句子合并为一个文档，也同时把标签都合并在一起。所以整个文档就有其对应的标签了，之后再基于序列标注的范式预测整个文档的标签。所以我不太理解您的意思？也因此遇到提交格式的困惑。希望您能指点一下。再次感谢您的悉心解答 @yaof20

**Comment by yaof20** [comment]
> 您好 感谢您的提醒! 我是把基于句子级别的标签都打上了之后（还没有id化），之后把属于一个文档中的句子合并为一个文档，也同时把标签都合并在一起。所以整个文档就有其对应的标签了，之后再基于序列标注的范式预测整个文档的标签。所以我不太理解您的意思？也因此遇到提交格式的困惑。希望您能指点一下。再次感谢您的悉心解答 @yaof20

假设以下3个句子同属于一个文档:
`S1 = [t1, t2, ..., t10]` (10个token) , 
`S2 = [t11, t12, ..., t30]` (20个token),
`S3 = [t31, t12, ..., t60]` (30个token),

合并后的文档为：
`D = S1 + S2 + S3 = [t1, t2, ..., t60]`，

对应原始句子的offset (文档里第i个token属于哪一个原始的句子):
offset_s1 = [1, 10]
offset_s2 = [11, 30]
offset_s3 = [31, 60]


对合并后的文档做inference（预测事件标签）：
`pred = [p1, p2, ..., p60]`

这里预测的每一个p_i都能按照对应的offset还原到原始的句子中，从而得到提交格式。

**Comment by Yyy11181** [comment]
再次打搅，抱歉！但是我试了一下这个想法，但是感觉行不通。主要是模型是按批次来训练和评估的。目前得到的pred是按批次储存的，当模型评估完所有的dev 数据之后，得到的pred是一个很大的矩阵，形如[899,512],前面是样本数量，后面是文本长度，因此无法去检索到其对应的文档是哪个文档。 @yaof20
