### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by Yyy11181** [thunlp/LEVEN#7]
嘿，您好，关于论文的源码有一个问题。
下面第一张图片中目录下runner中的mode=test_local ,是指什么啊？代码部分如下
我可以理解为从验证集中分割的一部分测试数据用于得到模型在测试数据上的表现吗
![image](https://user-images.githubusercontent.com/96362397/206716498-d4e7dd4f-85b4-4961-9501-18b2b8f4100c.png)
![ZY)B8M{CG_~QB IA6DQ@$BH](https://user-images.githubusercontent.com/96362397/206717389-cc23e863-f1c6-41be-bd35-50361b369a04.png)

**Comment by yaof20** [comment]
您好，这里的“test_local”是指：为了方便做实验，使用的是有标签的test set（公开数据时隐藏了）

这个repo的代码稍微有点乱，可以参考我们新发布的OmniEvent工具包，里面提供了比较清洁的实现（支持LEVEN以及其他的event数据集）

**Comment by Yyy11181** [comment]
好的 谢谢你
