### ISSUE TITLE
Downstream 资料前处理是否缺少檔案？

### ISSUE THREAD

**Issue by raysun0729** [thunlp/LEVEN#8]
您好，不好意思打扰您。
想请问在Downstream资料夹中，进入LJP资料前处理，看README说明有提到要执行 python predict.py 程式，不过在资料夹中并没有看到有这份程式码，请问能提供predict.py这份code吗？谢谢

**Comment by yaof20** [comment]
> 您好，不好意思打扰您。 想请问在Downstream资料夹中，进入LJP资料前处理，看README说明有提到要执行 python predict.py 程式，不过在资料夹中并没有看到有这份程式码，请问能提供predict.py这份code吗？谢谢

您好，感谢对我们工作的关注。
此处的 `predict.py` 是指资料夹中的 `process.py`. 相应的文档已经更新，请参考[这里](https://github.com/thunlp/LEVEN/tree/main/Downstreams/LJP/LJP-Preprocess#usage)

**Comment by raysun0729** [comment]
![image](https://user-images.githubusercontent.com/49860466/213247934-77ea4166-8d8d-4bf1-8765-39fa2bf4ddb1.png)
您好，不好意思想再请教问题，我对于你们这项研究很有兴趣，这是很棒的研究。

我执行Process.py程式后，出现如图所示的Error，想请问这部分能如何解决呢?不好意思打扰。

**Comment by yaof20** [comment]
> ![image](https://user-images.githubusercontent.com/49860466/213247934-77ea4166-8d8d-4bf1-8765-39fa2bf4ddb1.png) 您好，不好意思想再请教问题，我对于你们这项研究很有兴趣，这是很棒的研究。
> 
> 我执行Process.py程式后，出现如图所示的Error，想请问这部分能如何解决呢?不好意思打扰。

您好，我自己测试了repo里提供的代码是可以运行的，没有复现出您提问的这个error.

您可以检查一下**路径**和**文件名**，其中CAIL2018数据集中的 `exercise_contest`文件夹对应的是`small`, `first_stage`对应的是`large`. (如文档所述，LEVEN论文使用的是small)

`input_data`文件夹和`output_data`文件夹结构相同，例如：`input_data/small/train.json`（注意修改文件名称）。

如仍有问题可以与我联系，我的邮箱是yaof20@mails.tsinghua.edu.cn
